import { useMemo, useState } from "react";
import { FlatList, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { useCloset } from "../../hooks/useCloset";
import type { RootStackParams } from "../../navigation/AppNavigator";
import { colors, radii, shadows, spacing, typography } from "../../theme/tokens";

export function ClosetScreen() {
  const { garments, loading, refresh, toggleFavorite } = useCloset();
  const [query, setQuery] = useState("");
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [category, setCategory] = useState<string | null>(null);
  const { width } = useWindowDimensions();
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParams>>();
  const columnCount = width >= 760 ? 3 : 2;
  const categories = useMemo(() => [...new Set(garments.map((garment) => garment.category))].sort(), [garments]);
  const items = useMemo(() => garments.filter((item) => (!favoritesOnly || item.isFavorite) && (!category || item.category === category) && `${item.name} ${item.category} ${item.color}`.toLowerCase().includes(query.toLowerCase())), [category, favoritesOnly, garments, query]);

  return <View style={styles.root}>
    <View style={styles.header}><View><Text style={styles.title}>Your Closet</Text><Text style={styles.copy}>{garments.length} considered {garments.length === 1 ? "piece" : "pieces"}</Text></View><Pressable accessibilityRole="button" accessibilityState={{ selected: favoritesOnly }} onPress={() => setFavoritesOnly((value) => !value)} style={[styles.filter, favoritesOnly ? styles.filterActive : undefined]}><Text style={[styles.filterText, favoritesOnly ? styles.filterTextActive : undefined]}>Favorites</Text></Pressable></View>
    <TextInput accessibilityLabel="Search closet" placeholder="Search your closet" placeholderTextColor={colors.textTertiary} value={query} onChangeText={setQuery} style={styles.search} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Pressable accessibilityRole="button" accessibilityState={{ selected: category === null }} onPress={() => setCategory(null)} style={[styles.categoryFilter, category === null ? styles.categoryFilterActive : undefined]}><Text style={[styles.categoryFilterText, category === null ? styles.categoryFilterTextActive : undefined]}>All</Text></Pressable>{categories.map((item) => <Pressable accessibilityRole="button" accessibilityState={{ selected: category === item }} key={item} onPress={() => setCategory(item)} style={[styles.categoryFilter, category === item ? styles.categoryFilterActive : undefined]}><Text style={[styles.categoryFilterText, category === item ? styles.categoryFilterTextActive : undefined]}>{item}</Text></Pressable>)}</ScrollView>
    {loading && garments.length === 0 ? <View style={styles.skeletonGrid}>{[0, 1, 2, 3].map((item) => <View key={item} style={styles.skeletonCard}><View style={styles.skeletonImage} /><View style={styles.skeletonLine} /></View>)}</View> : <FlatList key={columnCount} contentContainerStyle={styles.list} columnWrapperStyle={items.length > columnCount ? styles.row : undefined} data={items} initialNumToRender={6} keyExtractor={(item) => item.id} maxToRenderPerBatch={6} numColumns={columnCount} removeClippedSubviews refreshControl={<RefreshControl refreshing={loading} onRefresh={refresh} tintColor={colors.brand} />} windowSize={5} ListEmptyComponent={<View style={styles.emptyCard}><Text style={styles.emptyTitle}>{query || favoritesOnly || category ? "No pieces found" : "Your closet is waiting"}</Text><Text style={styles.empty}>{query || favoritesOnly || category ? "Try a different search or filter." : "Capture a garment to begin your personal edit."}</Text></View>} renderItem={({ item }) => <View style={styles.cardWrap}><Pressable accessibilityRole="button" accessibilityLabel={`View ${item.name}`} onPress={() => navigation.navigate("GarmentDetails", { garmentId: item.id })} style={styles.card}><Image accessibilityLabel={item.name} source={{ uri: item.imageUri }} style={styles.image} /><View style={styles.cardContent}><Text numberOfLines={1} style={styles.name}>{item.name}</Text><Text numberOfLines={1} style={styles.category}>{item.category} · {item.color}</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={item.isFavorite ? `Remove ${item.name} from favorites` : `Favorite ${item.name}`} onPress={() => void toggleFavorite(item.id)} style={styles.favoriteButton}><Text style={styles.favorite}>{item.isFavorite ? "★" : "☆"}</Text></Pressable></View>} />}
  </View>;
}

const styles = StyleSheet.create({ root: { backgroundColor: colors.canvas, flex: 1, paddingHorizontal: spacing.lg }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingTop: spacing.xl }, title: { ...typography.display, color: colors.textPrimary }, copy: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs }, search: { ...typography.body, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.medium, borderWidth: 1, color: colors.textPrimary, marginTop: spacing.lg, paddingHorizontal: spacing.lg, paddingVertical: spacing.md }, filters: { gap: spacing.sm, paddingVertical: spacing.md }, categoryFilter: { borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, categoryFilterActive: { backgroundColor: colors.brand, borderColor: colors.brand }, categoryFilterText: { ...typography.caption, color: colors.textSecondary }, categoryFilterTextActive: { color: colors.brandForeground }, filter: { borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, filterActive: { backgroundColor: colors.brand, borderColor: colors.brand }, filterText: { ...typography.caption, color: colors.textSecondary }, filterTextActive: { color: colors.brandForeground }, list: { gap: spacing.md, paddingBottom: spacing.xxxl, paddingTop: spacing.sm }, row: { gap: spacing.md }, cardWrap: { flex: 1, position: "relative" }, card: { ...shadows.card, backgroundColor: colors.surface, borderRadius: radii.medium, overflow: "hidden" }, image: { backgroundColor: colors.imagePlaceholder, height: 190, width: "100%" }, cardContent: { gap: spacing.xs, padding: spacing.md }, favoriteButton: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radii.pill, height: 32, justifyContent: "center", position: "absolute", right: spacing.sm, top: spacing.sm, width: 32 }, favorite: { color: colors.brand, fontSize: 18 }, name: { ...typography.bodyBold, color: colors.textPrimary }, category: { ...typography.caption, color: colors.textSecondary }, emptyCard: { backgroundColor: colors.surface, borderRadius: radii.large, gap: spacing.sm, marginTop: spacing.xl, padding: spacing.xl }, emptyTitle: { ...typography.subheading, color: colors.textPrimary }, empty: { ...typography.body, color: colors.textSecondary }, skeletonGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md, paddingTop: spacing.lg }, skeletonCard: { backgroundColor: colors.surface, borderRadius: radii.medium, flexGrow: 1, minWidth: "44%", overflow: "hidden" }, skeletonImage: { backgroundColor: colors.surfaceMuted, height: 190 }, skeletonLine: { backgroundColor: colors.surfaceMuted, borderRadius: radii.small, height: 16, margin: spacing.md, width: "58%" } });
